In [1]:
import numpy as np
import sys

### The Basics

#### Why NumPy over lists?

- Fixed type of data : no element wise type check
- Allows to fix size of arrays : faster to read less bytes of memory
- Contiguous memory : Allows SIMD vector processing, effective cache utilization
- Tons of operations and functions

In [9]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 8.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 8.]]


In [6]:
#Get dimension
a.ndim

1

In [7]:
#Get shape
b.shape

(2, 3)

In [10]:
#Get type
a.dtype

dtype('int16')

In [13]:
#Get size (bytes)
a.itemsize #2
b.itemsize #8

8

In [12]:
#Get total size(bytes)
a.nbytes

6

### Accesing and changing rows, columns, elements...

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [17]:
a[1, 5]  #0-indexed

13

In [18]:
a[1, -2] #note , is differnt from python [][]

13

In [19]:
#Get a row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Get a col
a[:, 2]

array([ 3, 10])

In [22]:
# Fancy slicing
a[0, 1:-1:2]     #start:end:step

array([2, 4, 6])

In [23]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [26]:
b = np.array([[[1,2], [3,4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
b[0,1,1]

4

In [28]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [29]:
b[:, 1, :] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of arrays

In [30]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
# All ones matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [36]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.46557604, 0.20066519],
       [0.93598585, 0.92481509],
       [0.99388113, 0.39532492],
       [0.66633057, 0.32435178]])

In [38]:
np.random.random_sample(a.shape)

array([[0.11567985, 0.45739049, 0.59143014, 0.28411424, 0.00959902,
        0.95080895, 0.76112363],
       [0.51599815, 0.40042401, 0.92306527, 0.54816233, 0.80951349,
        0.79722097, 0.51615292]])

In [39]:
# Random integers
np.random.randint(7, size = (3,3)) #upto 7

array([[0, 1, 1],
       [1, 6, 1],
       [5, 3, 2]])

In [40]:
np.random.randint(1,8,size = (2,2))

array([[6, 3],
       [6, 1]])

In [41]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [52]:
# Example
c = np.ones((5,5))
print(c)

c[1:-1, 1:-1] = 0
print(c)

c[2,2] = 9
print(c)

#alternate, construct np.zeros, add 9, merge

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [54]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)    #!!

[100   2   3]


In [57]:
a = np.array([2,3,4])
b = a.copy()
b[0] = 99
print(a)

[2 3 4]


### Math

In [58]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [59]:
a+2

array([3, 4, 5, 6])

In [60]:
a-2

array([-1,  0,  1,  2])

In [61]:
a*2

array([2, 4, 6, 8])

In [62]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [63]:
a+=2

In [64]:
print(a)

[3 4 5 6]


In [65]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [66]:
a**2

array([ 9, 16, 25, 36])

In [67]:
#Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [68]:
np.cos(a)  #look at scipy math routines for more!

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear Algebra

In [70]:
#Multiply matrices
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)


np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [71]:
#det      inv, eigen also available : look at scipy linalg
c = np.identity(3)
np.linalg.det(c)

1.0

### Stats

In [73]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.min(stats)

1

In [75]:
np.max(stats, axis = 1)

array([3, 6])

Axis: 0 means rows, 1 means cols.
In above code, axis = 1, means all axis 1 entities(columns) collapse into one.

### Reorganising Arrays

In [77]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

(2, 4)


In [79]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [80]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
# Vertically stack
v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,7])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [82]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Loading data

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata.astype('int32')

#### Advanced Indexing and Bool masks

In [89]:
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
c==0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [91]:
c[c==0]

array([0., 0., 0., 0., 0., 0.])

In [93]:
# Index with list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [94]:
np.any(c>0, axis = 0)

array([ True,  True,  True])

In [98]:
 ((c>-1) & (c<1))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [100]:
#example
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
print(a)

#task: get 2,8,14,20 diag

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [106]:
(a[0:4, 1:5])[np.identity(4)==1]

array([ 2,  8, 14, 20])

In [107]:
a[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [110]:
#task 4,5, 24,25, 29,30
a[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])